export const LICENSE_TYPE_LABELS: Record<string, string> = {
  COMMERCIAL_BANK: "Commercial Bank",
  MICROFINANCE_INSTITUTION_TIER1: "Microfinance Institution Tier 1",
  MICROFINANCE_INSTITUTION_TIER2: "Microfinance Institution Tier 2",
  SAVINGS_CREDIT_COOPERATIVE: "Savings & Credit Cooperative (SACCO)",
  FOREX_BUREAU: "Forex Bureau",
  PAYMENT_SERVICE_PROVIDER: "Payment Service Provider (PSP)",
  DEVELOPMENT_FINANCE_INSTITUTION: "Development Finance Institution",
  REPRESENTATIVE_OFFICE: "Representative Office",
};

export const APPLICATION_STATUS_LABELS: Record<string, string> = {
  DRAFT: "Draft",
  NAME_APPROVAL_PENDING: "Name Approval Pending",
  NAME_APPROVED: "Name Approved",
  NAME_REJECTED: "Name Rejected",
  SUBMITTED: "Submitted",
  COMPLETENESS_CHECK: "Completeness Check",
  INCOMPLETE: "Incomplete",
  CASE_ASSIGNED: "Case Assigned",
  FIT_AND_PROPER_ASSESSMENT: "Fit & Proper Assessment",
  TECHNICAL_REVIEW: "Technical Review",
  LEGAL_REVIEW: "Legal Review",
  ADDITIONAL_INFO_REQUESTED: "Additional Info Requested",
  COMMITTEE_DELIBERATION: "Committee Deliberation",
  APPROVAL_IN_PRINCIPLE: "Approval in Principle",
  ORGANIZATION_PERIOD: "Organization Period",
  PRE_LICENSE_INSPECTION: "Pre-License Inspection",
  INSPECTION_FAILED: "Inspection Failed",
  LICENSE_FEE_PENDING: "License Fee Pending",
  LICENSED: "Licensed",
  REJECTED: "Rejected",
  AIP_EXPIRED: "AIP Expired",
  WITHDRAWN: "Withdrawn",
};
