export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  BUSINESS_PLAN: "BUSINESS PLAN (3-YEAR PROJECTION)",
  ARTICLES_OF_INCORPORATION: "ARTICLES OF INCORPORATION",
  SUPPORTING_DOC: "SUPPORTING DOCUMENTS",
  AML_CFT_POLICY: "AML/CFT POLICY",
  AML_CFT_COMPLIANCE_MANUAL: "AML/CFT COMPLIANCE MANUAL",
  PREMISES_OWNERSHIP_OR_LEASE: "PREMISES OWNERSHIP OR LEASE",
  FIT_AND_PROPER_DECLARATIONS_ALL_DIRECTORS: "FIT AND PROPER DECLARATIONS ALL DIRECTORS",
  TAX_CLEARANCE_CERTIFICATE: "TAX CLEARANCE CERTIFICATE",
  GOVERNANCE_CHARTER: "GOVERNANCE CHARTER",
  IT_SECURITY_POLICY: "IT SECURITY POLICY",
  RISK_MANAGEMENT_FRAMEWORK: "RISK MANAGEMENT FRAMEWORK",
  INTERNAL_AUDIT_CHARTER: "INTERNAL AUDIT CHARTER",
  CREDIT_INFORMATION_BUREAU_CLEARANCE: "CREDIT INFORMATION BUREAU CLEARANCE",
  FEASIBILITY_STUDY: "FEASIBILITY STUDY",
  SHAREHOLDERS_REGISTRY: "SHAREHOLDERS REGISTRY",
  PROOF_OF_FUNDS_SOURCE: "PROOF OF FUNDS SOURCE",
};

export const REQUIRED_DOCUMENTS: Record<string, string[]> = {
  COMMERCIAL_BANK: [
    "BUSINESS_PLAN",
    "FEASIBILITY_STUDY",
    "SHAREHOLDERS_REGISTRY",
    "PROOF_OF_FUNDS_SOURCE",
    "GOVERNANCE_CHARTER",
    "ARTICLES_OF_INCORPORATION",
    "AML_CFT_POLICY",
    "IT_SECURITY_POLICY",
    "RISK_MANAGEMENT_FRAMEWORK",
    "INTERNAL_AUDIT_CHARTER",
    "FIT_AND_PROPER_DECLARATIONS_ALL_DIRECTORS",
    "CREDIT_INFORMATION_BUREAU_CLEARANCE",
    "TAX_CLEARANCE_CERTIFICATE"
  ],
  MICROFINANCE_INSTITUTION_TIER1: [
    "BUSINESS_PLAN",
    // ... (simplified for brevity, but we can expand if needed)
  ],
  MICROFINANCE_INSTITUTION_TIER2: [
    "BUSINESS_PLAN",
  ],
  SAVINGS_CREDIT_COOPERATIVE: [
    "BUSINESS_PLAN",
  ],
  FOREX_BUREAU: [
    "BUSINESS_PLAN",
    "AML_CFT_COMPLIANCE_MANUAL",
    "PREMISES_OWNERSHIP_OR_LEASE",
    "ARTICLES_OF_INCORPORATION",
    "FIT_AND_PROPER_DECLARATIONS_ALL_DIRECTORS",
    "TAX_CLEARANCE_CERTIFICATE"
  ],
  PAYMENT_SERVICE_PROVIDER: [
    "BUSINESS_PLAN",
  ],
  DEVELOPMENT_FINANCE_INSTITUTION: [
    "BUSINESS_PLAN",
  ],
  REPRESENTATIVE_OFFICE: [
    "BUSINESS_PLAN",
  ],
};