-- Create schemas
CREATE SCHEMA IF NOT EXISTS bnr;
CREATE SCHEMA IF NOT EXISTS audit;
SET SCHEMA bnr;

-- User Roles
CREATE TYPE user_role AS ENUM (
    'APPLICANT',
    'CASE_MANAGER',
    'COMPLIANCE_OFFICER',
    'TECHNICAL_REVIEWER',
    'FIT_AND_PROPER_OFFICER',
    'LEGAL_OFFICER',
    'INSPECTION_OFFICER',
    'LICENSING_COMMITTEE',
    'GOVERNOR_DELEGATE',
    'ADMIN',
    'AUDITOR'
);

-- License Types
CREATE TYPE license_type AS ENUM (
    'COMMERCIAL_BANK',
    'MICROFINANCE_INSTITUTION_TIER1',
    'MICROFINANCE_INSTITUTION_TIER2',
    'SAVINGS_CREDIT_COOPERATIVE',
    'FOREX_BUREAU',
    'PAYMENT_SERVICE_PROVIDER',
    'DEVELOPMENT_FINANCE_INSTITUTION',
    'REPRESENTATIVE_OFFICE'
);

-- Application Statuses
CREATE TYPE application_status AS ENUM (
    'DRAFT',
    'NAME_APPROVAL_PENDING',
    'NAME_APPROVED',
    'SUBMITTED',
    'COMPLETENESS_CHECK',
    'INCOMPLETE',
    'CASE_ASSIGNED',
    'FIT_AND_PROPER_ASSESSMENT',
    'TECHNICAL_REVIEW',
    'ADDITIONAL_INFO_REQUESTED',
    'LEGAL_REVIEW',
    'COMMITTEE_DELIBERATION',
    'APPROVAL_IN_PRINCIPLE',
    'ORGANIZATION_PERIOD',
    'PRE_LICENSE_INSPECTION',
    'INSPECTION_FAILED',
    'LICENSE_FEE_PENDING',
    'LICENSED',
    'REJECTED',
    'WITHDRAWN',
    'AIP_EXPIRED'
);

-- Audit Actions
CREATE TYPE audit_action AS ENUM (
    'APPLICATION_CREATED', 'NAME_APPROVAL_REQUESTED', 'NAME_APPROVED', 'NAME_REJECTED',
    'APPLICATION_SUBMITTED', 'COMPLETENESS_CHECK_STARTED', 'COMPLETENESS_PASSED',
    'COMPLETENESS_FAILED', 'CASE_MANAGER_ASSIGNED', 'FIT_AND_PROPER_STARTED',
    'FIT_AND_PROPER_COMPLETED', 'TECHNICAL_REVIEW_STARTED', 'ADDITIONAL_INFO_REQUESTED',
    'ADDITIONAL_INFO_PROVIDED', 'TECHNICAL_REVIEW_COMPLETED', 'LEGAL_REVIEW_STARTED',
    'LEGAL_REVIEW_COMPLETED', 'COMMITTEE_DELIBERATION_STARTED',
    'APPROVAL_IN_PRINCIPLE_GRANTED', 'APPROVAL_IN_PRINCIPLE_DENIED',
    'ORGANIZATION_PERIOD_STARTED', 'INSPECTION_SCHEDULED', 'INSPECTION_PASSED',
    'INSPECTION_FAILED', 'LICENSE_FEE_RECEIVED', 'LICENSE_ISSUED',
    'APPLICATION_REJECTED', 'APPLICATION_WITHDRAWN', 'AIP_EXPIRED',
    'SLA_CLOCK_PAUSED', 'SLA_CLOCK_RESUMED', 'CONDITION_ADDED',
    'CONDITION_FULFILLED', 'DOCUMENT_UPLOADED', 'DOCUMENT_VERSION_ADDED',
    'USER_CREATED', 'USER_DEACTIVATED', 'REVIEWER_REASSIGNED'
);
