CREATE TABLE bnr.applications (
    id UUID PRIMARY KEY,
    reference_number VARCHAR(30) UNIQUE NOT NULL,
    applicant_id UUID NOT NULL,
    license_type VARCHAR(64) NOT NULL,
    institution_name VARCHAR(255) NOT NULL,
    proposed_name VARCHAR(255),
    proposed_capital_rwf BIGINT NOT NULL,
    registered_country VARCHAR(100) NOT NULL DEFAULT 'Rwanda',
    head_office_address CLOB,
    is_foreign_institution BOOLEAN NOT NULL DEFAULT FALSE,
    home_supervisor_name VARCHAR(255),
    home_supervisor_email VARCHAR(255),
    status VARCHAR(64) NOT NULL DEFAULT 'DRAFT',
    version INTEGER NOT NULL DEFAULT 1,
    case_manager_id UUID,
    compliance_officer_id UUID,
    technical_reviewer_id UUID,
    legal_officer_id UUID,
    inspection_officer_id UUID,
    sla_working_days_target INTEGER NOT NULL DEFAULT 90,
    sla_clock_started_at TIMESTAMP WITH TIME ZONE,
    sla_clock_paused_at TIMESTAMP WITH TIME ZONE,
    sla_working_days_used INTEGER NOT NULL DEFAULT 0,
    sla_paused_reason CLOB,
    aip_granted_at TIMESTAMP WITH TIME ZONE,
    aip_granted_by UUID,
    aip_expires_at TIMESTAMP WITH TIME ZONE,
    organization_deadline TIMESTAMP WITH TIME ZONE,
    license_fee_paid_at TIMESTAMP WITH TIME ZONE,
    license_issued_at TIMESTAMP WITH TIME ZONE,
    license_issued_by UUID,
    license_number VARCHAR(30),
    completeness_notes CLOB,
    info_requested_reason CLOB,
    technical_review_notes CLOB,
    legal_review_notes CLOB,
    rejection_reason CLOB,
    final_status_at TIMESTAMP WITH TIME ZONE,
    submitted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_applications_status ON bnr.applications(status);
CREATE INDEX idx_applications_applicant ON bnr.applications(applicant_id);
CREATE INDEX idx_applications_ref ON bnr.applications(reference_number);
