package rw.bnr.licensing.domain.enums;

public enum ApplicationStatus {
    DRAFT,
    NAME_APPROVAL_PENDING,
    NAME_APPROVED,
    SUBMITTED,
    COMPLETENESS_CHECK,
    INCOMPLETE,
    CASE_ASSIGNED,
    FIT_AND_PROPER_ASSESSMENT,
    TECHNICAL_REVIEW,
    ADDITIONAL_INFO_REQUESTED,
    LEGAL_REVIEW,
    COMMITTEE_DELIBERATION,
    APPROVAL_IN_PRINCIPLE,
    ORGANIZATION_PERIOD,
    PRE_LICENSE_INSPECTION,
    INSPECTION_FAILED,
    LICENSE_FEE_PENDING,
    LICENSED,
    REJECTED,
    WITHDRAWN,
    AIP_EXPIRED
}
