package rw.bnr.licensing.domain.enums;

public enum LicenseType {
    COMMERCIAL_BANK,
    MICROFINANCE_INSTITUTION_TIER1,
    MICROFINANCE_INSTITUTION_TIER2,
    SAVINGS_CREDIT_COOPERATIVE,
    FOREX_BUREAU,
    PAYMENT_SERVICE_PROVIDER,
    DEVELOPMENT_FINANCE_INSTITUTION,
    REPRESENTATIVE_OFFICE
}
